update workflow

diff --git a/.github/workflows/validate-submissions.yml b/.github/workflows/validate-submissions.yml
--- a/.github/workflows/validate-submissions.yml
+++ b/.github/workflows/validate-submissions.yml
@@ -63,13 +63,14 @@ jobs:
             -o "$TTL_FILE" -vvv \
             2>&1 | tee "$LOG_FILE"
 
-          echo "ttl_file=$TTL_FILE" >> $GITHUB_ENV
-          echo "log_file=$LOG_FILE" >> $GITHUB_ENV
+          echo "TTL_FILE=$TTL_FILE" >> $GITHUB_ENV
+          echo "LOG_FILE=$LOG_FILE" >> $GITHUB_ENV
+          
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
 
-          git add "$ttl_file" || echo "⚠️ TTL not found"
-          git add "$log_file" || echo "⚠️ Log not found"
+          git add "$TTL_FILE" || echo "⚠️ TTL not found"
+          git add "$LOG_FILE" || echo "⚠️ Log not found"
           
           if git diff --cached --quiet; then
             echo "✅ No changes to commit."
@@ -79,13 +80,13 @@ jobs:
           fi
 
       - name: Run SHACL Validation
-        if: env.ttl_file != ''
+        if: env.TTL_FILE != ''
         run: |
-          result_file="${ttl_file%.ttl}.md"
-          shape_file="Submissions/shapes/$(basename $(dirname "$ttl_file")).ttl"
+          result_file="${TTL_FILE%.ttl}.md"
+          shape_file="Submissions/shapes/$(basename $(dirname "$TTL_FILE")).ttl"
 
-          echo "🔍 Validating: $ttl_file"
-          python -m pyshacl -s "$shape_file" -df auto -sf turtle -f human "$ttl_file" > "$result_file"
+          echo "🔍 Validating: $TTL_FILE"
+          python -m pyshacl -s "$shape_file" -df auto -sf turtle -f human "$TTL_FILE" > "$result_file"
 
           echo "result_file=$result_file" >> $GITHUB_ENV
           
