solve a mistake

diff --git a/.github/workflows/validate-submissions.yml b/.github/workflows/validate-submissions.yml
--- a/.github/workflows/validate-submissions.yml
+++ b/.github/workflows/validate-submissions.yml
@@ -73,7 +73,7 @@ jobs:
             2>&1 | tee "$LOG_FILE_REASONING"
 
           echo "TTL_FILE=$TTL_FILE" >> $GITHUB_ENV
-          echo "LOG_FILE_REASONING=$LOG_FILE_REASONING" >> $GITHUB_ENV
+          echo "TTL_FILE_REASONED=$TTL_FILE_REASONED" >> $GITHUB_ENV
           echo "LOG_FILE=$LOG_FILE" >> $GITHUB_ENV
           echo "LOG_FILE_REASONING=$LOG_FILE_REASONING" >> $GITHUB_ENV
 
@@ -81,7 +81,7 @@ jobs:
           git config user.email "github-actions@github.com"
 
           git add "$TTL_FILE" || echo "⚠️ TTL not found"
-          git add "$LOG_FILE_REASONING" || echo "⚠️ Reasoned TTL not found"
+          git add "$TTL_FILE_REASONED" || echo "⚠️ Reasoned TTL not found"
           git add "$LOG_FILE" || echo "⚠️ Log not found"
           git add "$LOG_FILE_REASONING" || echo "⚠️ Reasoner Log not found"
           
